from typing import Dict, Any
import os
from .context_generator import ContextGenerator

class ScaffoldGenerator:
    """Generates project scaffolds based on tech stack."""
    
    @classmethod
    def generate(cls, config: Dict[str, Any]) -> Dict[str, str]:
        """Generate project files."""
        tech_stack = config.get("tech_stack", "").lower()
        
        if "next.js" in tech_stack:
            return cls._generate_nextjs(config)
        else:
            return cls._generate_nextjs(config) # Default to Next.js for now

    @classmethod
    def _generate_nextjs(cls, config: Dict[str, Any]) -> Dict[str, str]:
        files = {}
        project_name = config.get("name", "my-app").lower().replace(" ", "-")
        
        # 1. package.json
        files["package.json"] = f"""{{
  "name": "{project_name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "next": "^14.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "@supabase/supabase-js": "^2.39.0"
  }},
  "devDependencies": {{
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.4.0",
    "typescript": "^5"
  }}
}}
"""
        # 2. next.config.js
        files["next.config.js"] = """module.exports = { reactStrictMode: true };
"""
        # 3. tailwind.config.ts
        files["tailwind.config.ts"] = """import type { Config } from "tailwindcss";
const config: Config = { content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"], theme: { extend: {} }, plugins: [] };
export default config;
"""
        # 4. postcss.config.js
        files["postcss.config.js"] = """module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };
"""
        # 5. tsconfig.json
        files["tsconfig.json"] = """{ "compilerOptions": { "target": "es5", "lib": ["dom", "dom.iterable", "esnext"], "allowJs": true, "skipLibCheck": true, "strict": true, "forceConsistentCasingInFileNames": true, "noEmit": true, "esModuleInterop": true, "module": "esnext", "moduleResolution": "bundler", "resolveJsonModule": true, "isolatedModules": true, "jsx": "preserve", "incremental": true, "plugins": [{ "name": "next" }], "paths": { "@/*": ["./*"] } }, "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"], "exclude": ["node_modules"] }
"""
        # 6. app/layout.tsx
        files["app/layout.tsx"] = """export const metadata = { title: "Ssuma App", description: "Generated by Ssuma" };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground antialiased">{children}</body>
    </html>
  );
}
"""
        # 7. app/page.tsx
        files["app/page.tsx"] = """export default function Home() { return <main className="p-8"><h1>Welcome to Ssuma App</h1></main>; }
"""
        # 8. app/globals.css
        files["app/globals.css"] = """@tailwind base; @tailwind components; @tailwind utilities;
"""
        # 9. Context files (A)
        context_files = ContextGenerator.generate(config)
        for name, content in context_files.items():
            files[f"docs/{name}"] = content
            
        # 10. AI IDE Rule files
        files[".cursorrules"] = f"""# AI IDE Rules for {project_name}
1. Always read `docs/context.md` first.
2. Follow the tech stack in `docs/tech_stack.md`.
3. Use TypeScript for all new files.
4. Use TailwindCSS for styling.
5. Do not hallucinate APIs or database schemas.
"""
        files["AGENTS.md"] = context_files.get("context.md", "")

        return files
